require: rubocop-rails
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - 'bin/**/*'
    - 'bin/*'
    - 'bundler_stubs/**/*'
    - 'cookbooks/**/*'
    - 'vendor/bundle/**/*'
    - 'Gemfile.lock'
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/LineLength:
  Enabled: false
Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter
Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Layout/ExtraSpacing:
  AllowForAlignment: true
  ForceEqualSignAlignment: false
Layout/SpaceAroundOperators:
  AllowForAlignment: true
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: true
Lint/EmptyConditionalBody:
  Enabled: true
Lint/FloatComparison:
  Enabled: true
Lint/MissingSuper:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: true
Lint/SelfAssignment:
  Enabled: true
Lint/TopLevelReturnWithArgument:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: true
Lint/DuplicateRequire:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 120
Metrics/ClassLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: true
  Max: 20
Metrics/PerceivedComplexity:
  Enabled: true
  Max: 20
Rails:
  Enabled: true
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/SkipsModelValidations:
  Enabled: False
Rails/UnknownEnv:
  Environments:
    - development
    - production
    - test
Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/FindById:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/PluckId:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedStyle: ruby19
Style/ClassVars:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/SlicingWithRange:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
  Exclude:
    - 'config/puma.rb'
Style/AccessorGrouping:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/CaseLikeIf:
  Enabled: true
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashLikeCase:
  Enabled: true
  MinBranchesCount: 4
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/ExplicitBlockArgument:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: true
Style/StringConcatenation:
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: true
Rails/WhereNot:
  Enabled: true
