---
:timeout: 30
:concurrency: 5
:queues:
  - mailers
  - default
  - reports
  - callfire
  - [mailchimp, 1]
  - [hubspot, 1]
:limits:
  mailers: 5
  default: 5
  reports: 5
  callfire: 5
  mailchimp: 1
  hubspot: 1
