---
:timeout: 30
:concurrency: 5
:queues:
  - high_priority
  - mailers
  - default
  - reports
  - callfire
  - rent_manager
  - rent_manager_webhook
  - notifications
  - [mailchimp, 1]
  - [hubspot, 1]
:limits:
  high_priority: 2
  mailers: 5
  default: 5
  reports: 5
  callfire: 5
  mailchimp: 1
  hubspot: 1
  rent_manager: 1
  rent_manager_webhook: 1
  notifications: 3
